site_name: Jagger | Blog
site_url: https://jagger235711.github.io/
site_description: Jagger 的个人博客
site_author: Jagger G

repo_url: https://github.com/jagger235711/jagger235711.github.io
repo_name: jagger235711/jagger235711.github.io
edit_uri: "edit/origin/docs/"

theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.follow
    - toc.integrate
  palette: #调整网页皮肤
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: 进入夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: 进入日间模式
  icon:
    repo: fontawesome/brands/github
plugins:
  # - meta
  - blog:
      post_date_format: full
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - git-revision-date-localized:
      enable_creation_date: true
  # - info: #出问题求助大佬时打最小包用
  #     enabled_on_serve: true
  - search:
      lang:
        - en
        - zh
      separator: '[\s\u200b\-]'
  - glightbox

# markdown_extensions:
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2023 Jagger G

# Page tree
nav:
  - 首页: index.md
  # - Getting started:
  #     - Installation: getting-started.md
  #     - Creating your site: creating-your-site.md
  #     - Publishing your site: publishing-your-site.md
  #     - Customization: customization.md
  #     - Conventions: conventions.md
  #     - Browser support: browser-support.md
  #     - Enterprise feedback: enterprise-support.md
  #     - Philosophy: philosophy.md
  #     - Alternatives: alternatives.md
  #     - License: license.md
  #     - Changelog:
  #         - changelog/index.md
  #         - How to upgrade: upgrade.md
  #     - Contributing:
  #         - contributing/index.md
  #         - Reporting a bug: contributing/reporting-a-bug.md
  #         - Reporting a docs issue: contributing/reporting-a-docs-issue.md
  #         - Requesting a change: contributing/requesting-a-change.md
  #         - Adding translations: contributing/adding-translations.md
  #         - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
  #     - Guides:
  #         - Creating a reproduction: guides/creating-a-reproduction.md
  #     - FAQ:
  #         - Sponsoring: faq/sponsoring.md
  # - Setup:
  #     - setup/index.md
  #     - Changing the colors: setup/changing-the-colors.md
  #     - Changing the fonts: setup/changing-the-fonts.md
  #     - Changing the language: setup/changing-the-language.md
  #     - Changing the logo and icons: setup/changing-the-logo-and-icons.md
  #     - Ensuring data privacy: setup/ensuring-data-privacy.md
  #     - Setting up navigation: setup/setting-up-navigation.md
  #     - Setting up site search: setup/setting-up-site-search.md
  #     - Setting up site analytics: setup/setting-up-site-analytics.md
  #     - Setting up social cards: setup/setting-up-social-cards.md
  #     - Setting up a blog: setup/setting-up-a-blog.md
  #     - Setting up tags: setup/setting-up-tags.md
  #     - Setting up versioning: setup/setting-up-versioning.md
  #     - Setting up the header: setup/setting-up-the-header.md
  #     - Setting up the footer: setup/setting-up-the-footer.md
  #     - Adding a git repository: setup/adding-a-git-repository.md
  #     - Adding a comment system: setup/adding-a-comment-system.md
  #     - Building an optimized site: setup/building-an-optimized-site.md
  #     - Building for offline usage: setup/building-for-offline-usage.md
  #     - Extensions:
  #         - setup/extensions/index.md
  #         - Python Markdown: setup/extensions/python-markdown.md
  #         - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
  # - Plugins:
  #     - plugins/index.md
  #     - Blog: plugins/blog.md
  #     - Group: plugins/group.md
  #     - Info: plugins/info.md
  #     - Meta: plugins/meta.md
  #     - Offline: plugins/offline.md
  #     - Optimize: plugins/optimize.md
  #     - Privacy: plugins/privacy.md
  #     - Projects: plugins/projects.md
  #     - Search: plugins/search.md
  #     - Social: plugins/social.md
  #     - Tags: plugins/tags.md
  #     - Typeset: plugins/typeset.md
  #     - Requirements:
  #         - Image processing: plugins/requirements/image-processing.md
  #         - Caching: plugins/requirements/caching.md
  # - Reference:
  #     - reference/index.md
  #     - Admonitions: reference/admonitions.md
  #     - Annotations: reference/annotations.md
  #     - Buttons: reference/buttons.md
  #     - Code blocks: reference/code-blocks.md
  #     - Content tabs: reference/content-tabs.md
  #     - Data tables: reference/data-tables.md
  #     - Diagrams: reference/diagrams.md
  #     - Footnotes: reference/footnotes.md
  #     - Formatting: reference/formatting.md
  #     - Grids: reference/grids.md
  #     - Icons, Emojis: reference/icons-emojis.md
  #     - Images: reference/images.md
  #     - Lists: reference/lists.md
  #     - Math: reference/math.md
  #     - Tooltips: reference/tooltips.md
  # - Insiders:
  #     - insiders/index.md
  #     - Getting started: insiders/getting-started.md
  #     - Changelog:
  #         - insiders/changelog/index.md
  #         - How to upgrade: insiders/upgrade.md
  - 博客:
      - blog/index.md
  - 关于我:
      - aboutMe/index.md
