site_name: Jagger | Blog
site_url: https://jagger235711.github.io/
site_description: Jagger 的个人博客
site_author: Jagger G

repo_url: https://github.com/jagger235711/jagger235711.github.io
repo_name: jagger235711/jagger235711.github.io
edit_uri: "edit/origin/docs/"

# nav:
#   - Index: index.md
#   #   - 标签分类: tags.md
#   - Archive:
#       - blog/

theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.prune
    - search.suggest
    - search.highlight
    - content.action.edit
    - toc.follow
    - toc.integrate
  palette: #调整网页皮肤
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: 进入夜间模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: 进入日间模式
  icon:
    repo: fontawesome/brands/github
plugins:
  # - meta
  - blog:
      post_date_format: full
      categories_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - git-revision-date-localized:
      enable_creation_date: true
  # - info: #出问题求助大佬时打最小包用
  #     enabled_on_serve: true
  - search:
      lang:
        - en
        - zh
      separator: '[\s\u200b\-]'

# markdown_extensions:
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - pymdownx.superfences
#   - admonition
#   - pymdownx.details
#   - pymdownx.superfences
copyright: Copyright &copy; 2023 Jagger G
